/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountLinkPostBody,
} from '../models/index';
import {
    AccountLinkPostBodyFromJSON,
    AccountLinkPostBodyToJSON,
} from '../models/index';

export interface AccountGetRequest {
    id: string;
}

export interface AccountLinkRequest {
    accountLinkPostBody: AccountLinkPostBody;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     */
    async accountCreateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/stripe/account`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountCreate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountCreateRaw(initOverrides);
    }

    /**
     */
    async accountGetRaw(requestParameters: AccountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling accountGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/stripe/account/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountGet(requestParameters: AccountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async accountLinkRaw(requestParameters: AccountLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['accountLinkPostBody'] == null) {
            throw new runtime.RequiredError(
                'accountLinkPostBody',
                'Required parameter "accountLinkPostBody" was null or undefined when calling accountLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/stripe/account/link`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountLinkPostBodyToJSON(requestParameters['accountLinkPostBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountLink(requestParameters: AccountLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountLinkRaw(requestParameters, initOverrides);
    }

}
