/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface CompletedWorkoutsCreateRequest {
    traineeId: string;
}

export interface CompletedWorkoutsDeleteRequest {
    traineeId: string;
    completedWorkoutId: string;
}

export interface CompletedWorkoutsGetRequest {
    traineeId: string;
}

export interface CompletedWorkoutsUpdateRequest {
    traineeId: string;
    completedWorkoutId: string;
}

/**
 * 
 */
export class CompletedWorkoutsApi extends runtime.BaseAPI {

    /**
     */
    async completedWorkoutsCreateRaw(requestParameters: CompletedWorkoutsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling completedWorkoutsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/completed-workouts`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completedWorkoutsCreate(requestParameters: CompletedWorkoutsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completedWorkoutsCreateRaw(requestParameters, initOverrides);
    }

    /**
     */
    async completedWorkoutsDeleteRaw(requestParameters: CompletedWorkoutsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling completedWorkoutsDelete().'
            );
        }

        if (requestParameters['completedWorkoutId'] == null) {
            throw new runtime.RequiredError(
                'completedWorkoutId',
                'Required parameter "completedWorkoutId" was null or undefined when calling completedWorkoutsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/completed-workouts/{completedWorkoutId}`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))).replace(`{${"completedWorkoutId"}}`, encodeURIComponent(String(requestParameters['completedWorkoutId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completedWorkoutsDelete(requestParameters: CompletedWorkoutsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completedWorkoutsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async completedWorkoutsGetRaw(requestParameters: CompletedWorkoutsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling completedWorkoutsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/completed-workouts`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completedWorkoutsGet(requestParameters: CompletedWorkoutsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completedWorkoutsGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async completedWorkoutsUpdateRaw(requestParameters: CompletedWorkoutsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling completedWorkoutsUpdate().'
            );
        }

        if (requestParameters['completedWorkoutId'] == null) {
            throw new runtime.RequiredError(
                'completedWorkoutId',
                'Required parameter "completedWorkoutId" was null or undefined when calling completedWorkoutsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/completed-workouts/{completedWorkoutId}`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))).replace(`{${"completedWorkoutId"}}`, encodeURIComponent(String(requestParameters['completedWorkoutId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completedWorkoutsUpdate(requestParameters: CompletedWorkoutsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completedWorkoutsUpdateRaw(requestParameters, initOverrides);
    }

}
