/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateExerciseCommand,
  ExerciseResponse,
  PaginatedResponseOfExerciseResponse,
  SearchExercisesRequest,
  StarExerciseRequest,
} from '../models/index';
import {
    CreateExerciseCommandFromJSON,
    CreateExerciseCommandToJSON,
    ExerciseResponseFromJSON,
    ExerciseResponseToJSON,
    PaginatedResponseOfExerciseResponseFromJSON,
    PaginatedResponseOfExerciseResponseToJSON,
    SearchExercisesRequestFromJSON,
    SearchExercisesRequestToJSON,
    StarExerciseRequestFromJSON,
    StarExerciseRequestToJSON,
} from '../models/index';

export interface ExercisesCreateRequest {
    createExerciseCommand: CreateExerciseCommand;
}

export interface ExercisesDeleteRequest {
    exerciseId: string;
}

export interface ExercisesGetRequest {
    cursor?: string;
}

export interface ExercisesSearchRequest {
    searchExercisesRequest: SearchExercisesRequest;
}

export interface ExercisesStarRequest {
    exerciseId: string;
    starExerciseRequest: StarExerciseRequest;
}

/**
 * 
 */
export class ExercisesApi extends runtime.BaseAPI {

    /**
     */
    async exercisesCreateRaw(requestParameters: ExercisesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExerciseResponse>> {
        if (requestParameters['createExerciseCommand'] == null) {
            throw new runtime.RequiredError(
                'createExerciseCommand',
                'Required parameter "createExerciseCommand" was null or undefined when calling exercisesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/exercises`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExerciseCommandToJSON(requestParameters['createExerciseCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExerciseResponseFromJSON(jsonValue));
    }

    /**
     */
    async exercisesCreate(requestParameters: ExercisesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExerciseResponse> {
        const response = await this.exercisesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async exercisesDeleteRaw(requestParameters: ExercisesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExerciseResponse>> {
        if (requestParameters['exerciseId'] == null) {
            throw new runtime.RequiredError(
                'exerciseId',
                'Required parameter "exerciseId" was null or undefined when calling exercisesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exercises/{exerciseId}`.replace(`{${"exerciseId"}}`, encodeURIComponent(String(requestParameters['exerciseId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExerciseResponseFromJSON(jsonValue));
    }

    /**
     */
    async exercisesDelete(requestParameters: ExercisesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExerciseResponse> {
        const response = await this.exercisesDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async exercisesGetRaw(requestParameters: ExercisesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseOfExerciseResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exercises`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseOfExerciseResponseFromJSON(jsonValue));
    }

    /**
     */
    async exercisesGet(requestParameters: ExercisesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseOfExerciseResponse> {
        const response = await this.exercisesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async exercisesOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exercises/options`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async exercisesOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exercisesOptionsRaw(initOverrides);
    }

    /**
     */
    async exercisesSearchRaw(requestParameters: ExercisesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseOfExerciseResponse>> {
        if (requestParameters['searchExercisesRequest'] == null) {
            throw new runtime.RequiredError(
                'searchExercisesRequest',
                'Required parameter "searchExercisesRequest" was null or undefined when calling exercisesSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/exercises/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchExercisesRequestToJSON(requestParameters['searchExercisesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseOfExerciseResponseFromJSON(jsonValue));
    }

    /**
     */
    async exercisesSearch(requestParameters: ExercisesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseOfExerciseResponse> {
        const response = await this.exercisesSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async exercisesStarRaw(requestParameters: ExercisesStarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['exerciseId'] == null) {
            throw new runtime.RequiredError(
                'exerciseId',
                'Required parameter "exerciseId" was null or undefined when calling exercisesStar().'
            );
        }

        if (requestParameters['starExerciseRequest'] == null) {
            throw new runtime.RequiredError(
                'starExerciseRequest',
                'Required parameter "starExerciseRequest" was null or undefined when calling exercisesStar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/exercises/{exerciseId}/star`.replace(`{${"exerciseId"}}`, encodeURIComponent(String(requestParameters['exerciseId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StarExerciseRequestToJSON(requestParameters['starExerciseRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async exercisesStar(requestParameters: ExercisesStarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exercisesStarRaw(requestParameters, initOverrides);
    }

    /**
     */
    async exercisesStarredRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseOfExerciseResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exercises/starred`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseOfExerciseResponseFromJSON(jsonValue));
    }

    /**
     */
    async exercisesStarred(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseOfExerciseResponse> {
        const response = await this.exercisesStarredRaw(initOverrides);
        return await response.value();
    }

}
