/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedResponseOfPlannedWorkoutResponse,
  PlannedWorkoutRequest,
  PlannedWorkoutResponse,
} from '../models/index';
import {
    PaginatedResponseOfPlannedWorkoutResponseFromJSON,
    PaginatedResponseOfPlannedWorkoutResponseToJSON,
    PlannedWorkoutRequestFromJSON,
    PlannedWorkoutRequestToJSON,
    PlannedWorkoutResponseFromJSON,
    PlannedWorkoutResponseToJSON,
} from '../models/index';

export interface PlannedWorkoutsCreateRequest {
    traineeId: string;
    plannedWorkoutRequest: PlannedWorkoutRequest;
}

export interface PlannedWorkoutsDeleteRequest {
    traineeId: string;
    plannedWorkoutId: string;
}

export interface PlannedWorkoutsGetRequest {
    traineeId: string;
    from?: Date;
    to?: Date;
    cursor?: string;
    limit?: number;
    sortBy?: Array<string>;
    order?: number;
}

export interface PlannedWorkoutsUpdateRequest {
    traineeId: string;
    plannedWorkoutId: string;
    plannedWorkoutRequest: PlannedWorkoutRequest;
}

/**
 * 
 */
export class PlannedWorkoutsApi extends runtime.BaseAPI {

    /**
     */
    async plannedWorkoutsCreateRaw(requestParameters: PlannedWorkoutsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlannedWorkoutResponse>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling plannedWorkoutsCreate().'
            );
        }

        if (requestParameters['plannedWorkoutRequest'] == null) {
            throw new runtime.RequiredError(
                'plannedWorkoutRequest',
                'Required parameter "plannedWorkoutRequest" was null or undefined when calling plannedWorkoutsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/trainees/{traineeId}/planned-workouts`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlannedWorkoutRequestToJSON(requestParameters['plannedWorkoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlannedWorkoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async plannedWorkoutsCreate(requestParameters: PlannedWorkoutsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlannedWorkoutResponse> {
        const response = await this.plannedWorkoutsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async plannedWorkoutsDeleteRaw(requestParameters: PlannedWorkoutsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling plannedWorkoutsDelete().'
            );
        }

        if (requestParameters['plannedWorkoutId'] == null) {
            throw new runtime.RequiredError(
                'plannedWorkoutId',
                'Required parameter "plannedWorkoutId" was null or undefined when calling plannedWorkoutsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/planned-workouts/{plannedWorkoutId}`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))).replace(`{${"plannedWorkoutId"}}`, encodeURIComponent(String(requestParameters['plannedWorkoutId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async plannedWorkoutsDelete(requestParameters: PlannedWorkoutsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.plannedWorkoutsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async plannedWorkoutsGetRaw(requestParameters: PlannedWorkoutsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseOfPlannedWorkoutResponse>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling plannedWorkoutsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/planned-workouts`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseOfPlannedWorkoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async plannedWorkoutsGet(requestParameters: PlannedWorkoutsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseOfPlannedWorkoutResponse> {
        const response = await this.plannedWorkoutsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async plannedWorkoutsUpdateRaw(requestParameters: PlannedWorkoutsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlannedWorkoutResponse>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling plannedWorkoutsUpdate().'
            );
        }

        if (requestParameters['plannedWorkoutId'] == null) {
            throw new runtime.RequiredError(
                'plannedWorkoutId',
                'Required parameter "plannedWorkoutId" was null or undefined when calling plannedWorkoutsUpdate().'
            );
        }

        if (requestParameters['plannedWorkoutRequest'] == null) {
            throw new runtime.RequiredError(
                'plannedWorkoutRequest',
                'Required parameter "plannedWorkoutRequest" was null or undefined when calling plannedWorkoutsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/trainees/{traineeId}/planned-workouts/{plannedWorkoutId}`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))).replace(`{${"plannedWorkoutId"}}`, encodeURIComponent(String(requestParameters['plannedWorkoutId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlannedWorkoutRequestToJSON(requestParameters['plannedWorkoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlannedWorkoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async plannedWorkoutsUpdate(requestParameters: PlannedWorkoutsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlannedWorkoutResponse> {
        const response = await this.plannedWorkoutsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
