/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignupRequest,
} from '../models/index';
import {
    SignupRequestFromJSON,
    SignupRequestToJSON,
} from '../models/index';

export interface SignupSignupRequest {
    signupRequest: SignupRequest;
}

/**
 * 
 */
export class SignupApi extends runtime.BaseAPI {

    /**
     */
    async signupSignupRaw(requestParameters: SignupSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signupRequest'] == null) {
            throw new runtime.RequiredError(
                'signupRequest',
                'Required parameter "signupRequest" was null or undefined when calling signupSignup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestToJSON(requestParameters['signupRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signupSignup(requestParameters: SignupSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signupSignupRaw(requestParameters, initOverrides);
    }

}
