/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TraineeInvitationsResponse,
} from '../models/index';
import {
    TraineeInvitationsResponseFromJSON,
    TraineeInvitationsResponseToJSON,
} from '../models/index';

export interface TraineeInvitationsAcceptRequest {
    traineeInvitationId: string;
}

export interface TraineeInvitationsDeclineRequest {
    traineeInvitationId: string;
}

/**
 * 
 */
export class TraineeInvitationsApi extends runtime.BaseAPI {

    /**
     */
    async traineeInvitationsAcceptRaw(requestParameters: TraineeInvitationsAcceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeInvitationId'] == null) {
            throw new runtime.RequiredError(
                'traineeInvitationId',
                'Required parameter "traineeInvitationId" was null or undefined when calling traineeInvitationsAccept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainee-invitations/{traineeInvitationId}/accept`.replace(`{${"traineeInvitationId"}}`, encodeURIComponent(String(requestParameters['traineeInvitationId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineeInvitationsAccept(requestParameters: TraineeInvitationsAcceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineeInvitationsAcceptRaw(requestParameters, initOverrides);
    }

    /**
     */
    async traineeInvitationsDeclineRaw(requestParameters: TraineeInvitationsDeclineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeInvitationId'] == null) {
            throw new runtime.RequiredError(
                'traineeInvitationId',
                'Required parameter "traineeInvitationId" was null or undefined when calling traineeInvitationsDecline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainee-invitations/{traineeInvitationId}/decline`.replace(`{${"traineeInvitationId"}}`, encodeURIComponent(String(requestParameters['traineeInvitationId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineeInvitationsDecline(requestParameters: TraineeInvitationsDeclineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineeInvitationsDeclineRaw(requestParameters, initOverrides);
    }

    /**
     */
    async traineeInvitationsGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TraineeInvitationsResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainee-invitations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TraineeInvitationsResponseFromJSON));
    }

    /**
     */
    async traineeInvitationsGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TraineeInvitationsResponse>> {
        const response = await this.traineeInvitationsGetAllRaw(initOverrides);
        return await response.value();
    }

}
