/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTraineeCommand,
  SimulateTraineeCostRequest,
  SimulateTraineeCostResponse,
  TraineeResponse,
  UpdateTraineeCostRequest,
} from '../models/index';
import {
    CreateTraineeCommandFromJSON,
    CreateTraineeCommandToJSON,
    SimulateTraineeCostRequestFromJSON,
    SimulateTraineeCostRequestToJSON,
    SimulateTraineeCostResponseFromJSON,
    SimulateTraineeCostResponseToJSON,
    TraineeResponseFromJSON,
    TraineeResponseToJSON,
    UpdateTraineeCostRequestFromJSON,
    UpdateTraineeCostRequestToJSON,
} from '../models/index';

export interface TraineesCancelRequest {
    traineeId: string;
}

export interface TraineesChargeRequest {
    traineeId: string;
}

export interface TraineesCostSimulateRequest {
    simulateTraineeCostRequest: SimulateTraineeCostRequest;
}

export interface TraineesCreateRequest {
    createTraineeCommand: CreateTraineeCommand;
}

export interface TraineesGetRequest {
    traineeId: string;
}

export interface TraineesUpdateCostRequest {
    traineeId: string;
    updateTraineeCostRequest: UpdateTraineeCostRequest;
}

/**
 * 
 */
export class TraineesApi extends runtime.BaseAPI {

    /**
     */
    async traineesCancelRaw(requestParameters: TraineesCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling traineesCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/cancel`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineesCancel(requestParameters: TraineesCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineesCancelRaw(requestParameters, initOverrides);
    }

    /**
     */
    async traineesChargeRaw(requestParameters: TraineesChargeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling traineesCharge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}/charge`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineesCharge(requestParameters: TraineesChargeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineesChargeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async traineesCostSimulateRaw(requestParameters: TraineesCostSimulateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimulateTraineeCostResponse>> {
        if (requestParameters['simulateTraineeCostRequest'] == null) {
            throw new runtime.RequiredError(
                'simulateTraineeCostRequest',
                'Required parameter "simulateTraineeCostRequest" was null or undefined when calling traineesCostSimulate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cost/simulate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimulateTraineeCostRequestToJSON(requestParameters['simulateTraineeCostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimulateTraineeCostResponseFromJSON(jsonValue));
    }

    /**
     */
    async traineesCostSimulate(requestParameters: TraineesCostSimulateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimulateTraineeCostResponse> {
        const response = await this.traineesCostSimulateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async traineesCreateRaw(requestParameters: TraineesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TraineeResponse>> {
        if (requestParameters['createTraineeCommand'] == null) {
            throw new runtime.RequiredError(
                'createTraineeCommand',
                'Required parameter "createTraineeCommand" was null or undefined when calling traineesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/trainees`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTraineeCommandToJSON(requestParameters['createTraineeCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TraineeResponseFromJSON(jsonValue));
    }

    /**
     */
    async traineesCreate(requestParameters: TraineesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TraineeResponse> {
        const response = await this.traineesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async traineesGetRaw(requestParameters: TraineesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling traineesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees/{traineeId}`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineesGet(requestParameters: TraineesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineesGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async traineesGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TraineeResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trainees`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TraineeResponseFromJSON));
    }

    /**
     */
    async traineesGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TraineeResponse>> {
        const response = await this.traineesGetAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async traineesUpdateCostRaw(requestParameters: TraineesUpdateCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['traineeId'] == null) {
            throw new runtime.RequiredError(
                'traineeId',
                'Required parameter "traineeId" was null or undefined when calling traineesUpdateCost().'
            );
        }

        if (requestParameters['updateTraineeCostRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTraineeCostRequest',
                'Required parameter "updateTraineeCostRequest" was null or undefined when calling traineesUpdateCost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/trainees/{traineeId}/cost`.replace(`{${"traineeId"}}`, encodeURIComponent(String(requestParameters['traineeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTraineeCostRequestToJSON(requestParameters['updateTraineeCostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async traineesUpdateCost(requestParameters: TraineesUpdateCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.traineesUpdateCostRaw(requestParameters, initOverrides);
    }

}
