using MassTransit;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Mjolksyra.Domain.Database;
using Mjolksyra.Domain.Database.Models;
using Mjolksyra.Domain.Messaging;
using Mjolksyra.Infrastructure.Messaging.Consumers;
using Mjolksyra.Infrastructure.R2;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Mjolksyra.Infrastructure.Tests.Messaging.Consumers;

public class MediaCompressConsumerTests
{
    private const string PublicBaseUrl = "https://media.example.com";

    private static Mock<ConsumeContext<MediaCompressionRequestedMessage>> BuildContext(
        string fileUrl,
        Guid? workoutId = null,
        Guid? chatMessageId = null)
    {
        var context = new Mock<ConsumeContext<MediaCompressionRequestedMessage>>();
        context.SetupGet(x => x.Message).Returns(new MediaCompressionRequestedMessage
        {
            FileUrl = fileUrl,
            CompletedWorkoutId = workoutId ?? Guid.NewGuid(),
            CompletedWorkoutChatMessageId = chatMessageId ?? Guid.NewGuid(),
        });
        context.SetupGet(x => x.CancellationToken).Returns(CancellationToken.None);
        return context;
    }

    [Fact]
    public async Task Consume_WhenDownloadFails_LogsWarningAndDoesNotThrow()
    {
        var httpClientFactory = new Mock<IHttpClientFactory>();
        httpClientFactory.Setup(x => x.CreateClient(It.IsAny<string>()))
            .Returns(new HttpClient(new FailingHandler()));

        var fileUploader = new Mock<IR2FileUploader>();
        var chatRepository = new Mock<ICompletedWorkoutChatMessageRepository>();

        var consumer = new MediaCompressConsumer(
            httpClientFactory.Object,
            fileUploader.Object,
            chatRepository.Object,
            NullLogger<MediaCompressConsumer>.Instance);

        // Should not throw — graceful degradation
        await consumer.Consume(BuildContext($"{PublicBaseUrl}/workouts/abc.webp?raw=1").Object);

        // Repository and uploader should not have been touched
        chatRepository.Verify(x => x.SetMediaCompressedUrl(It.IsAny<Guid>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
        fileUploader.Verify(x => x.UploadAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Consume_WhenUploadFails_LogsWarningAndDoesNotThrow()
    {
        var httpClientFactory = new Mock<IHttpClientFactory>();
        httpClientFactory.Setup(x => x.CreateClient(It.IsAny<string>()))
            .Returns(new HttpClient(new FakeImageHandler()));

        var fileUploader = new Mock<IR2FileUploader>();
        fileUploader
            .Setup(x => x.UploadAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new InvalidOperationException("upload failed"));

        var chatRepository = new Mock<ICompletedWorkoutChatMessageRepository>();

        var consumer = new MediaCompressConsumer(
            httpClientFactory.Object,
            fileUploader.Object,
            chatRepository.Object,
            NullLogger<MediaCompressConsumer>.Instance);

        // Should not throw
        await consumer.Consume(BuildContext($"{PublicBaseUrl}/workouts/abc.webp?raw=1").Object);

        chatRepository.Verify(x => x.SetMediaCompressedUrl(It.IsAny<Guid>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Consume_OnSuccess_SetsCompressedUrlOnChatMessage()
    {
        var workoutId = Guid.NewGuid();
        var chatMessageId = Guid.NewGuid();
        var rawUrl = $"{PublicBaseUrl}/workouts/rawkey123.webp?raw=1";
        var compressedUrl = $"{PublicBaseUrl}/workouts/compressedkey456.webp";

        var httpClientFactory = new Mock<IHttpClientFactory>();
        httpClientFactory.Setup(x => x.CreateClient(It.IsAny<string>()))
            .Returns(new HttpClient(new FakeImageHandler()));

        var fileUploader = new Mock<IR2FileUploader>();
        fileUploader
            .Setup(x => x.UploadAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(compressedUrl);

        var chatRepository = new Mock<ICompletedWorkoutChatMessageRepository>();

        var consumer = new MediaCompressConsumer(
            httpClientFactory.Object,
            fileUploader.Object,
            chatRepository.Object,
            NullLogger<MediaCompressConsumer>.Instance);

        await consumer.Consume(BuildContext(rawUrl, workoutId: workoutId, chatMessageId: chatMessageId).Object);

        chatRepository.Verify(x => x.SetMediaCompressedUrl(chatMessageId, rawUrl, compressedUrl, CancellationToken.None), Times.Once);
    }

    // Valid 1×1 PNG generated by ImageSharp (correct CRCs guaranteed)
    private static readonly byte[] MinimalPngBytes = CreateValidPng();

    private static byte[] CreateValidPng()
    {
        using var image = new Image<Rgba32>(1, 1, new Rgba32(255, 0, 0));
        using var ms = new MemoryStream();
        image.SaveAsPng(ms);
        return ms.ToArray();
    }

    private class FailingHandler : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct)
            => throw new HttpRequestException("Simulated network error");
    }

    private class FakeImageHandler : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct)
        {
            var response = new HttpResponseMessage(System.Net.HttpStatusCode.OK)
            {
                Content = new ByteArrayContent(MinimalPngBytes)
            };
            response.Content.Headers.ContentType =
                new System.Net.Http.Headers.MediaTypeHeaderValue("image/png");
            return Task.FromResult(response);
        }
    }
}
