"use client";

import { PageSectionHeader } from "@/components/Navigation/PageSectionHeader";
import { useTraineeInsights } from "@/hooks/useTraineeInsights";
import {
  InsightsAccordion,
  hasRenderableInsights,
} from "@/components/TraineeInsights/InsightsAccordion";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";

type Props = {
  traineeId: string;
};

export function AthleteInsights({ traineeId }: Props) {
  const { data: insights } = useTraineeInsights(traineeId);
  const hasInsightsContent = hasRenderableInsights(insights);
  const showPendingRefreshNotice =
    insights?.status === "pending" && hasInsightsContent;

  const generatedAt = insights?.generatedAt
    ? new Date(insights.generatedAt).toLocaleDateString("sv-SE", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : null;

  return (
    <div className="space-y-8 pb-8">
      <PageSectionHeader
        eyebrow="Intelligence"
        title="Your Insights"
        titleClassName="text-xl md:text-2xl"
        description={
          generatedAt
            ? `Last updated ${generatedAt}`
            : "Insights are generated by your coach."
        }
      />

      {showPendingRefreshNotice ? (
        <Alert>
          <AlertTitle>Refreshing insights…</AlertTitle>
          <AlertDescription>
            Your previous insights stay visible until the updated version is ready.
          </AlertDescription>
        </Alert>
      ) : null}

      {!insights || (insights.status === "pending" && !hasInsightsContent) ? (
        <Alert>
          <AlertTitle>
            {insights?.status === "pending"
              ? "Generating insights…"
              : "No insights available yet."}
          </AlertTitle>
          <AlertDescription>
            {insights?.status === "pending"
              ? "This may take a moment. The page will update automatically."
              : "Your coach will generate insights once you have completed enough workouts."}
          </AlertDescription>
        </Alert>
      ) : insights.status === "failed" ? (
        <Alert variant="destructive">
          <AlertTitle>Insights generation failed.</AlertTitle>
          <AlertDescription>Your coach can retry from the coach portal.</AlertDescription>
        </Alert>
      ) : !insights.visibleToAthlete ? (
        <Alert>
          <AlertTitle>Insights are not yet shared.</AlertTitle>
          <AlertDescription>
            Your coach will make your insights visible when ready.
          </AlertDescription>
        </Alert>
      ) : (
        <InsightsAccordion insights={insights} />
      )}
    </div>
  );
}
