/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountLinkPostBody
 */
export interface AccountLinkPostBody {
    /**
     * 
     * @type {string}
     * @memberof AccountLinkPostBody
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof AccountLinkPostBody
     */
    baseUrl: string;
}

/**
 * Check if a given object implements the AccountLinkPostBody interface.
 */
export function instanceOfAccountLinkPostBody(value: object): value is AccountLinkPostBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    return true;
}

export function AccountLinkPostBodyFromJSON(json: any): AccountLinkPostBody {
    return AccountLinkPostBodyFromJSONTyped(json, false);
}

export function AccountLinkPostBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLinkPostBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'baseUrl': json['baseUrl'],
    };
}

export function AccountLinkPostBodyToJSON(json: any): AccountLinkPostBody {
    return AccountLinkPostBodyToJSONTyped(json, false);
}

export function AccountLinkPostBodyToJSONTyped(value?: AccountLinkPostBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'baseUrl': value['baseUrl'],
    };
}

