/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTraineeCommand
 */
export interface CreateTraineeCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateTraineeCommand
     */
    athleteUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTraineeCommand
     */
    coachUserId: string;
}

/**
 * Check if a given object implements the CreateTraineeCommand interface.
 */
export function instanceOfCreateTraineeCommand(value: object): value is CreateTraineeCommand {
    if (!('athleteUserId' in value) || value['athleteUserId'] === undefined) return false;
    if (!('coachUserId' in value) || value['coachUserId'] === undefined) return false;
    return true;
}

export function CreateTraineeCommandFromJSON(json: any): CreateTraineeCommand {
    return CreateTraineeCommandFromJSONTyped(json, false);
}

export function CreateTraineeCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTraineeCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'athleteUserId': json['athleteUserId'],
        'coachUserId': json['coachUserId'],
    };
}

export function CreateTraineeCommandToJSON(json: any): CreateTraineeCommand {
    return CreateTraineeCommandToJSONTyped(json, false);
}

export function CreateTraineeCommandToJSONTyped(value?: CreateTraineeCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'athleteUserId': value['athleteUserId'],
        'coachUserId': value['coachUserId'],
    };
}

