/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExerciseCommand
 */
export interface CreateExerciseCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    force?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    mechanic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    equipment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseCommand
     */
    category?: string | null;
}

/**
 * Check if a given object implements the CreateExerciseCommand interface.
 */
export function instanceOfCreateExerciseCommand(value: object): value is CreateExerciseCommand {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateExerciseCommandFromJSON(json: any): CreateExerciseCommand {
    return CreateExerciseCommandFromJSONTyped(json, false);
}

export function CreateExerciseCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExerciseCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'force': json['force'] == null ? undefined : json['force'],
        'level': json['level'] == null ? undefined : json['level'],
        'mechanic': json['mechanic'] == null ? undefined : json['mechanic'],
        'equipment': json['equipment'] == null ? undefined : json['equipment'],
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function CreateExerciseCommandToJSON(json: any): CreateExerciseCommand {
    return CreateExerciseCommandToJSONTyped(json, false);
}

export function CreateExerciseCommandToJSONTyped(value?: CreateExerciseCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'force': value['force'],
        'level': value['level'],
        'mechanic': value['mechanic'],
        'equipment': value['equipment'],
        'category': value['category'],
    };
}

