/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseResponse
 */
export interface ExerciseResponse {
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    force: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    level: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    mechanic: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    equipment: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    category: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseResponse
     */
    instructions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseResponse
     */
    primaryMuscles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseResponse
     */
    secondaryMuscles: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ExerciseResponse
     */
    starred: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExerciseResponse
     */
    canDelete: boolean;
}

/**
 * Check if a given object implements the ExerciseResponse interface.
 */
export function instanceOfExerciseResponse(value: object): value is ExerciseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('force' in value) || value['force'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('mechanic' in value) || value['mechanic'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('primaryMuscles' in value) || value['primaryMuscles'] === undefined) return false;
    if (!('secondaryMuscles' in value) || value['secondaryMuscles'] === undefined) return false;
    if (!('starred' in value) || value['starred'] === undefined) return false;
    if (!('canDelete' in value) || value['canDelete'] === undefined) return false;
    return true;
}

export function ExerciseResponseFromJSON(json: any): ExerciseResponse {
    return ExerciseResponseFromJSONTyped(json, false);
}

export function ExerciseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'force': json['force'],
        'level': json['level'],
        'mechanic': json['mechanic'],
        'equipment': json['equipment'],
        'category': json['category'],
        'instructions': json['instructions'],
        'primaryMuscles': json['primaryMuscles'],
        'secondaryMuscles': json['secondaryMuscles'],
        'starred': json['starred'],
        'canDelete': json['canDelete'],
    };
}

export function ExerciseResponseToJSON(json: any): ExerciseResponse {
    return ExerciseResponseToJSONTyped(json, false);
}

export function ExerciseResponseToJSONTyped(value?: ExerciseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'force': value['force'],
        'level': value['level'],
        'mechanic': value['mechanic'],
        'equipment': value['equipment'],
        'category': value['category'],
        'instructions': value['instructions'],
        'primaryMuscles': value['primaryMuscles'],
        'secondaryMuscles': value['secondaryMuscles'],
        'starred': value['starred'],
        'canDelete': value['canDelete'],
    };
}

