/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCommand
 */
export interface LoginCommand {
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    password: string;
}

/**
 * Check if a given object implements the LoginCommand interface.
 */
export function instanceOfLoginCommand(value: object): value is LoginCommand {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginCommandFromJSON(json: any): LoginCommand {
    return LoginCommandFromJSONTyped(json, false);
}

export function LoginCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginCommandToJSON(json: any): LoginCommand {
    return LoginCommandToJSONTyped(json, false);
}

export function LoginCommandToJSONTyped(value?: LoginCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

