/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LoginResponse
     */
    refreshTokenExpiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken?: string | null;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccessful': json['isSuccessful'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpiresAt': json['refreshTokenExpiresAt'] == null ? undefined : (new Date(json['refreshTokenExpiresAt'])),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSuccessful': value['isSuccessful'],
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'] == null ? undefined : ((value['refreshTokenExpiresAt'] as any).toISOString()),
        'accessToken': value['accessToken'],
    };
}

