/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExerciseResponse } from './ExerciseResponse';
import {
    ExerciseResponseFromJSON,
    ExerciseResponseFromJSONTyped,
    ExerciseResponseToJSON,
    ExerciseResponseToJSONTyped,
} from './ExerciseResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseOfExerciseResponse
 */
export interface PaginatedResponseOfExerciseResponse {
    /**
     * 
     * @type {Array<ExerciseResponse>}
     * @memberof PaginatedResponseOfExerciseResponse
     */
    data: Array<ExerciseResponse>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseOfExerciseResponse
     */
    next: string | null;
}

/**
 * Check if a given object implements the PaginatedResponseOfExerciseResponse interface.
 */
export function instanceOfPaginatedResponseOfExerciseResponse(value: object): value is PaginatedResponseOfExerciseResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    return true;
}

export function PaginatedResponseOfExerciseResponseFromJSON(json: any): PaginatedResponseOfExerciseResponse {
    return PaginatedResponseOfExerciseResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfExerciseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfExerciseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ExerciseResponseFromJSON)),
        'next': json['next'],
    };
}

export function PaginatedResponseOfExerciseResponseToJSON(json: any): PaginatedResponseOfExerciseResponse {
    return PaginatedResponseOfExerciseResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfExerciseResponseToJSONTyped(value?: PaginatedResponseOfExerciseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ExerciseResponseToJSON)),
        'next': value['next'],
    };
}

