/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlannedWorkoutResponse } from './PlannedWorkoutResponse';
import {
    PlannedWorkoutResponseFromJSON,
    PlannedWorkoutResponseFromJSONTyped,
    PlannedWorkoutResponseToJSON,
    PlannedWorkoutResponseToJSONTyped,
} from './PlannedWorkoutResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseOfPlannedWorkoutResponse
 */
export interface PaginatedResponseOfPlannedWorkoutResponse {
    /**
     * 
     * @type {Array<PlannedWorkoutResponse>}
     * @memberof PaginatedResponseOfPlannedWorkoutResponse
     */
    data: Array<PlannedWorkoutResponse>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseOfPlannedWorkoutResponse
     */
    next: string | null;
}

/**
 * Check if a given object implements the PaginatedResponseOfPlannedWorkoutResponse interface.
 */
export function instanceOfPaginatedResponseOfPlannedWorkoutResponse(value: object): value is PaginatedResponseOfPlannedWorkoutResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    return true;
}

export function PaginatedResponseOfPlannedWorkoutResponseFromJSON(json: any): PaginatedResponseOfPlannedWorkoutResponse {
    return PaginatedResponseOfPlannedWorkoutResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfPlannedWorkoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfPlannedWorkoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PlannedWorkoutResponseFromJSON)),
        'next': json['next'],
    };
}

export function PaginatedResponseOfPlannedWorkoutResponseToJSON(json: any): PaginatedResponseOfPlannedWorkoutResponse {
    return PaginatedResponseOfPlannedWorkoutResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfPlannedWorkoutResponseToJSONTyped(value?: PaginatedResponseOfPlannedWorkoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PlannedWorkoutResponseToJSON)),
        'next': value['next'],
    };
}

