/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlannedExerciseRequest
 */
export interface PlannedExerciseRequest {
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseRequest
     */
    exerciseId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the PlannedExerciseRequest interface.
 */
export function instanceOfPlannedExerciseRequest(value: object): value is PlannedExerciseRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PlannedExerciseRequestFromJSON(json: any): PlannedExerciseRequest {
    return PlannedExerciseRequestFromJSONTyped(json, false);
}

export function PlannedExerciseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedExerciseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'exerciseId': json['exerciseId'] == null ? undefined : json['exerciseId'],
        'name': json['name'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PlannedExerciseRequestToJSON(json: any): PlannedExerciseRequest {
    return PlannedExerciseRequestToJSONTyped(json, false);
}

export function PlannedExerciseRequestToJSONTyped(value?: PlannedExerciseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'exerciseId': value['exerciseId'],
        'name': value['name'],
        'note': value['note'],
    };
}

