/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlannedExerciseResponse
 */
export interface PlannedExerciseResponse {
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    exerciseId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    note: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    force: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    level: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    mechanic: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    equipment: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExerciseResponse
     */
    category: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlannedExerciseResponse
     */
    instructions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlannedExerciseResponse
     */
    primaryMuscles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlannedExerciseResponse
     */
    secondaryMuscles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlannedExerciseResponse
     */
    images: Array<string>;
}

/**
 * Check if a given object implements the PlannedExerciseResponse interface.
 */
export function instanceOfPlannedExerciseResponse(value: object): value is PlannedExerciseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('exerciseId' in value) || value['exerciseId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('force' in value) || value['force'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('mechanic' in value) || value['mechanic'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('primaryMuscles' in value) || value['primaryMuscles'] === undefined) return false;
    if (!('secondaryMuscles' in value) || value['secondaryMuscles'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function PlannedExerciseResponseFromJSON(json: any): PlannedExerciseResponse {
    return PlannedExerciseResponseFromJSONTyped(json, false);
}

export function PlannedExerciseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedExerciseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'exerciseId': json['exerciseId'],
        'name': json['name'],
        'note': json['note'],
        'force': json['force'],
        'level': json['level'],
        'mechanic': json['mechanic'],
        'equipment': json['equipment'],
        'category': json['category'],
        'instructions': json['instructions'],
        'primaryMuscles': json['primaryMuscles'],
        'secondaryMuscles': json['secondaryMuscles'],
        'images': json['images'],
    };
}

export function PlannedExerciseResponseToJSON(json: any): PlannedExerciseResponse {
    return PlannedExerciseResponseToJSONTyped(json, false);
}

export function PlannedExerciseResponseToJSONTyped(value?: PlannedExerciseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'exerciseId': value['exerciseId'],
        'name': value['name'],
        'note': value['note'],
        'force': value['force'],
        'level': value['level'],
        'mechanic': value['mechanic'],
        'equipment': value['equipment'],
        'category': value['category'],
        'instructions': value['instructions'],
        'primaryMuscles': value['primaryMuscles'],
        'secondaryMuscles': value['secondaryMuscles'],
        'images': value['images'],
    };
}

