/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlannedExerciseRequest } from './PlannedExerciseRequest';
import {
    PlannedExerciseRequestFromJSON,
    PlannedExerciseRequestFromJSONTyped,
    PlannedExerciseRequestToJSON,
    PlannedExerciseRequestToJSONTyped,
} from './PlannedExerciseRequest';

/**
 * 
 * @export
 * @interface PlannedWorkoutRequest
 */
export interface PlannedWorkoutRequest {
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutRequest
     */
    note?: string | null;
    /**
     * 
     * @type {Array<PlannedExerciseRequest>}
     * @memberof PlannedWorkoutRequest
     */
    exercises: Array<PlannedExerciseRequest>;
    /**
     * 
     * @type {Date}
     * @memberof PlannedWorkoutRequest
     */
    plannedAt?: Date;
}

/**
 * Check if a given object implements the PlannedWorkoutRequest interface.
 */
export function instanceOfPlannedWorkoutRequest(value: object): value is PlannedWorkoutRequest {
    if (!('exercises' in value) || value['exercises'] === undefined) return false;
    return true;
}

export function PlannedWorkoutRequestFromJSON(json: any): PlannedWorkoutRequest {
    return PlannedWorkoutRequestFromJSONTyped(json, false);
}

export function PlannedWorkoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedWorkoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'exercises': ((json['exercises'] as Array<any>).map(PlannedExerciseRequestFromJSON)),
        'plannedAt': json['plannedAt'] == null ? undefined : (new Date(json['plannedAt'])),
    };
}

export function PlannedWorkoutRequestToJSON(json: any): PlannedWorkoutRequest {
    return PlannedWorkoutRequestToJSONTyped(json, false);
}

export function PlannedWorkoutRequestToJSONTyped(value?: PlannedWorkoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'note': value['note'],
        'exercises': ((value['exercises'] as Array<any>).map(PlannedExerciseRequestToJSON)),
        'plannedAt': value['plannedAt'] == null ? undefined : ((value['plannedAt']).toISOString().substring(0,10)),
    };
}

