/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlannedExerciseResponse } from './PlannedExerciseResponse';
import {
    PlannedExerciseResponseFromJSON,
    PlannedExerciseResponseFromJSONTyped,
    PlannedExerciseResponseToJSON,
    PlannedExerciseResponseToJSONTyped,
} from './PlannedExerciseResponse';

/**
 * 
 * @export
 * @interface PlannedWorkoutResponse
 */
export interface PlannedWorkoutResponse {
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutResponse
     */
    traineeId: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedWorkoutResponse
     */
    note: string | null;
    /**
     * 
     * @type {Array<PlannedExerciseResponse>}
     * @memberof PlannedWorkoutResponse
     */
    exercises: Array<PlannedExerciseResponse>;
    /**
     * 
     * @type {Date}
     * @memberof PlannedWorkoutResponse
     */
    plannedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlannedWorkoutResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PlannedWorkoutResponse interface.
 */
export function instanceOfPlannedWorkoutResponse(value: object): value is PlannedWorkoutResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('traineeId' in value) || value['traineeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('exercises' in value) || value['exercises'] === undefined) return false;
    if (!('plannedAt' in value) || value['plannedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PlannedWorkoutResponseFromJSON(json: any): PlannedWorkoutResponse {
    return PlannedWorkoutResponseFromJSONTyped(json, false);
}

export function PlannedWorkoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedWorkoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'traineeId': json['traineeId'],
        'name': json['name'],
        'note': json['note'],
        'exercises': ((json['exercises'] as Array<any>).map(PlannedExerciseResponseFromJSON)),
        'plannedAt': (new Date(json['plannedAt'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function PlannedWorkoutResponseToJSON(json: any): PlannedWorkoutResponse {
    return PlannedWorkoutResponseToJSONTyped(json, false);
}

export function PlannedWorkoutResponseToJSONTyped(value?: PlannedWorkoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'traineeId': value['traineeId'],
        'name': value['name'],
        'note': value['note'],
        'exercises': ((value['exercises'] as Array<any>).map(PlannedExerciseResponseToJSON)),
        'plannedAt': ((value['plannedAt']).toISOString().substring(0,10)),
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

