/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshCommand
 */
export interface RefreshCommand {
    /**
     * 
     * @type {string}
     * @memberof RefreshCommand
     */
    refreshToken: string | null;
}

/**
 * Check if a given object implements the RefreshCommand interface.
 */
export function instanceOfRefreshCommand(value: object): value is RefreshCommand {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshCommandFromJSON(json: any): RefreshCommand {
    return RefreshCommandFromJSONTyped(json, false);
}

export function RefreshCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshCommandToJSON(json: any): RefreshCommand {
    return RefreshCommandToJSONTyped(json, false);
}

export function RefreshCommandToJSONTyped(value?: RefreshCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

