/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshResponse
 */
export interface RefreshResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RefreshResponse
     */
    isSuccessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RefreshResponse
     */
    refreshTokenExpiresAt?: Date | null;
}

/**
 * Check if a given object implements the RefreshResponse interface.
 */
export function instanceOfRefreshResponse(value: object): value is RefreshResponse {
    return true;
}

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccessful': json['isSuccessful'] == null ? undefined : json['isSuccessful'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpiresAt': json['refreshTokenExpiresAt'] == null ? undefined : (new Date(json['refreshTokenExpiresAt'])),
    };
}

export function RefreshResponseToJSON(json: any): RefreshResponse {
    return RefreshResponseToJSONTyped(json, false);
}

export function RefreshResponseToJSONTyped(value?: RefreshResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSuccessful': value['isSuccessful'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'] == null ? undefined : ((value['refreshTokenExpiresAt'] as any).toISOString()),
    };
}

