/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterResponse
     */
    isSuccessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RegisterResponse
     */
    refreshTokenExpiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    accessToken?: string | null;
}

/**
 * Check if a given object implements the RegisterResponse interface.
 */
export function instanceOfRegisterResponse(value: object): value is RegisterResponse {
    return true;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
    return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccessful': json['isSuccessful'] == null ? undefined : json['isSuccessful'],
        'error': json['error'] == null ? undefined : json['error'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpiresAt': json['refreshTokenExpiresAt'] == null ? undefined : (new Date(json['refreshTokenExpiresAt'])),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function RegisterResponseToJSON(json: any): RegisterResponse {
    return RegisterResponseToJSONTyped(json, false);
}

export function RegisterResponseToJSONTyped(value?: RegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSuccessful': value['isSuccessful'],
        'error': value['error'],
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'] == null ? undefined : ((value['refreshTokenExpiresAt'] as any).toISOString()),
        'accessToken': value['accessToken'],
    };
}

