/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCommand
 */
export interface RegisterCommand {
    /**
     * 
     * @type {string}
     * @memberof RegisterCommand
     */
    givenName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCommand
     */
    familyName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCommand
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCommand
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCommand
     */
    confirmPassword: string;
}

/**
 * Check if a given object implements the RegisterCommand interface.
 */
export function instanceOfRegisterCommand(value: object): value is RegisterCommand {
    if (!('givenName' in value) || value['givenName'] === undefined) return false;
    if (!('familyName' in value) || value['familyName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    return true;
}

export function RegisterCommandFromJSON(json: any): RegisterCommand {
    return RegisterCommandFromJSONTyped(json, false);
}

export function RegisterCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'givenName': json['givenName'],
        'familyName': json['familyName'],
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function RegisterCommandToJSON(json: any): RegisterCommand {
    return RegisterCommandToJSONTyped(json, false);
}

export function RegisterCommandToJSONTyped(value?: RegisterCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'givenName': value['givenName'],
        'familyName': value['familyName'],
        'email': value['email'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
    };
}

