/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchExercisesRequest
 */
export interface SearchExercisesRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchExercisesRequest
     */
    freeText: string;
}

/**
 * Check if a given object implements the SearchExercisesRequest interface.
 */
export function instanceOfSearchExercisesRequest(value: object): value is SearchExercisesRequest {
    if (!('freeText' in value) || value['freeText'] === undefined) return false;
    return true;
}

export function SearchExercisesRequestFromJSON(json: any): SearchExercisesRequest {
    return SearchExercisesRequestFromJSONTyped(json, false);
}

export function SearchExercisesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchExercisesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'freeText': json['freeText'],
    };
}

export function SearchExercisesRequestToJSON(json: any): SearchExercisesRequest {
    return SearchExercisesRequestToJSONTyped(json, false);
}

export function SearchExercisesRequestToJSONTyped(value?: SearchExercisesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'freeText': value['freeText'],
    };
}

