/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulateTraineeCostResponse
 */
export interface SimulateTraineeCostResponse {
    /**
     * 
     * @type {number}
     * @memberof SimulateTraineeCostResponse
     */
    applicationFee?: number;
    /**
     * 
     * @type {number}
     * @memberof SimulateTraineeCostResponse
     */
    coach?: number;
    /**
     * 
     * @type {number}
     * @memberof SimulateTraineeCostResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the SimulateTraineeCostResponse interface.
 */
export function instanceOfSimulateTraineeCostResponse(value: object): value is SimulateTraineeCostResponse {
    return true;
}

export function SimulateTraineeCostResponseFromJSON(json: any): SimulateTraineeCostResponse {
    return SimulateTraineeCostResponseFromJSONTyped(json, false);
}

export function SimulateTraineeCostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateTraineeCostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationFee': json['applicationFee'] == null ? undefined : json['applicationFee'],
        'coach': json['coach'] == null ? undefined : json['coach'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SimulateTraineeCostResponseToJSON(json: any): SimulateTraineeCostResponse {
    return SimulateTraineeCostResponseToJSONTyped(json, false);
}

export function SimulateTraineeCostResponseToJSONTyped(value?: SimulateTraineeCostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationFee': value['applicationFee'],
        'coach': value['coach'],
        'total': value['total'],
    };
}

