/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulateTraineeCostRequest
 */
export interface SimulateTraineeCostRequest {
    /**
     * 
     * @type {number}
     * @memberof SimulateTraineeCostRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the SimulateTraineeCostRequest interface.
 */
export function instanceOfSimulateTraineeCostRequest(value: object): value is SimulateTraineeCostRequest {
    return true;
}

export function SimulateTraineeCostRequestFromJSON(json: any): SimulateTraineeCostRequest {
    return SimulateTraineeCostRequestFromJSONTyped(json, false);
}

export function SimulateTraineeCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateTraineeCostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function SimulateTraineeCostRequestToJSON(json: any): SimulateTraineeCostRequest {
    return SimulateTraineeCostRequestToJSONTyped(json, false);
}

export function SimulateTraineeCostRequestToJSONTyped(value?: SimulateTraineeCostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

