/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StarExerciseRequest
 */
export interface StarExerciseRequest {
    /**
     * 
     * @type {boolean}
     * @memberof StarExerciseRequest
     */
    state: boolean;
}

/**
 * Check if a given object implements the StarExerciseRequest interface.
 */
export function instanceOfStarExerciseRequest(value: object): value is StarExerciseRequest {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function StarExerciseRequestFromJSON(json: any): StarExerciseRequest {
    return StarExerciseRequestFromJSONTyped(json, false);
}

export function StarExerciseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarExerciseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
    };
}

export function StarExerciseRequestToJSON(json: any): StarExerciseRequest {
    return StarExerciseRequestToJSONTyped(json, false);
}

export function StarExerciseRequestToJSONTyped(value?: StarExerciseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
    };
}

