/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraineeInvitationCoach
 */
export interface TraineeInvitationCoach {
    /**
     * 
     * @type {string}
     * @memberof TraineeInvitationCoach
     */
    givenName: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeInvitationCoach
     */
    familyName: string;
}

/**
 * Check if a given object implements the TraineeInvitationCoach interface.
 */
export function instanceOfTraineeInvitationCoach(value: object): value is TraineeInvitationCoach {
    if (!('givenName' in value) || value['givenName'] === undefined) return false;
    if (!('familyName' in value) || value['familyName'] === undefined) return false;
    return true;
}

export function TraineeInvitationCoachFromJSON(json: any): TraineeInvitationCoach {
    return TraineeInvitationCoachFromJSONTyped(json, false);
}

export function TraineeInvitationCoachFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeInvitationCoach {
    if (json == null) {
        return json;
    }
    return {
        
        'givenName': json['givenName'],
        'familyName': json['familyName'],
    };
}

export function TraineeInvitationCoachToJSON(json: any): TraineeInvitationCoach {
    return TraineeInvitationCoachToJSONTyped(json, false);
}

export function TraineeInvitationCoachToJSONTyped(value?: TraineeInvitationCoach | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'givenName': value['givenName'],
        'familyName': value['familyName'],
    };
}

