/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraineeUserResponse } from './TraineeUserResponse';
import {
    TraineeUserResponseFromJSON,
    TraineeUserResponseFromJSONTyped,
    TraineeUserResponseToJSON,
    TraineeUserResponseToJSONTyped,
} from './TraineeUserResponse';
import type { TraineePriceResponse } from './TraineePriceResponse';
import {
    TraineePriceResponseFromJSON,
    TraineePriceResponseFromJSONTyped,
    TraineePriceResponseToJSON,
    TraineePriceResponseToJSONTyped,
} from './TraineePriceResponse';

/**
 * 
 * @export
 * @interface TraineeResponse
 */
export interface TraineeResponse {
    /**
     * 
     * @type {string}
     * @memberof TraineeResponse
     */
    id: string;
    /**
     * 
     * @type {TraineeUserResponse}
     * @memberof TraineeResponse
     */
    coach: TraineeUserResponse;
    /**
     * 
     * @type {TraineeUserResponse}
     * @memberof TraineeResponse
     */
    athlete: TraineeUserResponse;
    /**
     * 
     * @type {TraineePriceResponse}
     * @memberof TraineeResponse
     */
    price: TraineePriceResponse | null;
    /**
     * 
     * @type {Date}
     * @memberof TraineeResponse
     */
    lastWorkoutAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TraineeResponse
     */
    nextWorkoutAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TraineeResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the TraineeResponse interface.
 */
export function instanceOfTraineeResponse(value: object): value is TraineeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('coach' in value) || value['coach'] === undefined) return false;
    if (!('athlete' in value) || value['athlete'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('lastWorkoutAt' in value) || value['lastWorkoutAt'] === undefined) return false;
    if (!('nextWorkoutAt' in value) || value['nextWorkoutAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TraineeResponseFromJSON(json: any): TraineeResponse {
    return TraineeResponseFromJSONTyped(json, false);
}

export function TraineeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'coach': TraineeUserResponseFromJSON(json['coach']),
        'athlete': TraineeUserResponseFromJSON(json['athlete']),
        'price': TraineePriceResponseFromJSON(json['price']),
        'lastWorkoutAt': (json['lastWorkoutAt'] == null ? null : new Date(json['lastWorkoutAt'])),
        'nextWorkoutAt': (json['nextWorkoutAt'] == null ? null : new Date(json['nextWorkoutAt'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function TraineeResponseToJSON(json: any): TraineeResponse {
    return TraineeResponseToJSONTyped(json, false);
}

export function TraineeResponseToJSONTyped(value?: TraineeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'coach': TraineeUserResponseToJSON(value['coach']),
        'athlete': TraineeUserResponseToJSON(value['athlete']),
        'price': TraineePriceResponseToJSON(value['price']),
        'lastWorkoutAt': (value['lastWorkoutAt'] == null ? null : (value['lastWorkoutAt'] as any).toISOString()),
        'nextWorkoutAt': (value['nextWorkoutAt'] == null ? null : (value['nextWorkoutAt'] as any).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

