/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraineeUserResponse
 */
export interface TraineeUserResponse {
    /**
     * 
     * @type {string}
     * @memberof TraineeUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeUserResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeUserResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeUserResponse
     */
    givenName: string | null;
    /**
     * 
     * @type {string}
     * @memberof TraineeUserResponse
     */
    familyName: string | null;
}

/**
 * Check if a given object implements the TraineeUserResponse interface.
 */
export function instanceOfTraineeUserResponse(value: object): value is TraineeUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('givenName' in value) || value['givenName'] === undefined) return false;
    if (!('familyName' in value) || value['familyName'] === undefined) return false;
    return true;
}

export function TraineeUserResponseFromJSON(json: any): TraineeUserResponse {
    return TraineeUserResponseFromJSONTyped(json, false);
}

export function TraineeUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'givenName': json['givenName'],
        'familyName': json['familyName'],
    };
}

export function TraineeUserResponseToJSON(json: any): TraineeUserResponse {
    return TraineeUserResponseToJSONTyped(json, false);
}

export function TraineeUserResponseToJSONTyped(value?: TraineeUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'givenName': value['givenName'],
        'familyName': value['familyName'],
    };
}

