/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraineePriceResponse
 */
export interface TraineePriceResponse {
    /**
     * 
     * @type {string}
     * @memberof TraineePriceResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof TraineePriceResponse
     */
    amount: number;
}

/**
 * Check if a given object implements the TraineePriceResponse interface.
 */
export function instanceOfTraineePriceResponse(value: object): value is TraineePriceResponse {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TraineePriceResponseFromJSON(json: any): TraineePriceResponse {
    return TraineePriceResponseFromJSONTyped(json, false);
}

export function TraineePriceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineePriceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'amount': json['amount'],
    };
}

export function TraineePriceResponseToJSON(json: any): TraineePriceResponse {
    return TraineePriceResponseToJSONTyped(json, false);
}

export function TraineePriceResponseToJSONTyped(value?: TraineePriceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'amount': value['amount'],
    };
}

