/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraineeInvitationCoach } from './TraineeInvitationCoach';
import {
    TraineeInvitationCoachFromJSON,
    TraineeInvitationCoachFromJSONTyped,
    TraineeInvitationCoachToJSON,
    TraineeInvitationCoachToJSONTyped,
} from './TraineeInvitationCoach';

/**
 * 
 * @export
 * @interface TraineeInvitationsResponse
 */
export interface TraineeInvitationsResponse {
    /**
     * 
     * @type {string}
     * @memberof TraineeInvitationsResponse
     */
    id?: string;
    /**
     * 
     * @type {TraineeInvitationCoach}
     * @memberof TraineeInvitationsResponse
     */
    coach: TraineeInvitationCoach;
    /**
     * 
     * @type {Date}
     * @memberof TraineeInvitationsResponse
     */
    acceptedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TraineeInvitationsResponse
     */
    rejectedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TraineeInvitationsResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the TraineeInvitationsResponse interface.
 */
export function instanceOfTraineeInvitationsResponse(value: object): value is TraineeInvitationsResponse {
    if (!('coach' in value) || value['coach'] === undefined) return false;
    return true;
}

export function TraineeInvitationsResponseFromJSON(json: any): TraineeInvitationsResponse {
    return TraineeInvitationsResponseFromJSONTyped(json, false);
}

export function TraineeInvitationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeInvitationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'coach': TraineeInvitationCoachFromJSON(json['coach']),
        'acceptedAt': json['acceptedAt'] == null ? undefined : (new Date(json['acceptedAt'])),
        'rejectedAt': json['rejectedAt'] == null ? undefined : (new Date(json['rejectedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function TraineeInvitationsResponseToJSON(json: any): TraineeInvitationsResponse {
    return TraineeInvitationsResponseToJSONTyped(json, false);
}

export function TraineeInvitationsResponseToJSONTyped(value?: TraineeInvitationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'coach': TraineeInvitationCoachToJSON(value['coach']),
        'acceptedAt': value['acceptedAt'] == null ? undefined : ((value['acceptedAt'] as any).toISOString()),
        'rejectedAt': value['rejectedAt'] == null ? undefined : ((value['rejectedAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

