/* tslint:disable */
/* eslint-disable */
/**
 * Mjolksyra.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTraineeCostRequest
 */
export interface UpdateTraineeCostRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateTraineeCostRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the UpdateTraineeCostRequest interface.
 */
export function instanceOfUpdateTraineeCostRequest(value: object): value is UpdateTraineeCostRequest {
    return true;
}

export function UpdateTraineeCostRequestFromJSON(json: any): UpdateTraineeCostRequest {
    return UpdateTraineeCostRequestFromJSONTyped(json, false);
}

export function UpdateTraineeCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTraineeCostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function UpdateTraineeCostRequestToJSON(json: any): UpdateTraineeCostRequest {
    return UpdateTraineeCostRequestToJSONTyped(json, false);
}

export function UpdateTraineeCostRequestToJSONTyped(value?: UpdateTraineeCostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

