// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './app/app/athlete/Athlete.fixture';
import * as fixture1 from './app/app/coach/Coach.fixture';

import * as decorator0 from './cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5001",
  "rendererUrl": "http://localhost:3000/cosmos/<fixture>"
};

const fixtures = {
  'app/app/athlete/Athlete.fixture.tsx': { module: fixture0 },
  'app/app/coach/Coach.fixture.tsx': { module: fixture1 }
};

const decorators = {
  'cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
